### ISSUE TITLE
Pattern matching taking more arguments

### ISSUE THREAD

**Issue by jakobnissen** [MasonProtter/SumTypes.jl#10]
I have a sum type like this:
```
@sum_type Indel begin
    Insertion()
    Deletion()
end

struct Edit
    pos::UInt
    x::Indel
end
```
And now I'd like to write a function with `Edit`, for a simple example, let's say I want to do this:
```
@case Indel report(()::Insertion, pos::UInt) = print("Insertion at position $pos")
@case Indel report(()::Deletion, pos::UInt) = print("Deletion at position $pos")
foo(x::Edit) = report(x.x, x.pos)
```

Unfortunately, I can't make this work - or something like that to work. One workaround is to do this:
```
@case Indel function report((x,)::Insertion)
    pos -> print("Insertion at position $pos")
end
foo(x::Edit) = report(x.x)(x.pos)
```
, and it does produce efficient code, but the syntax is very weird. @MasonProtter have you got any suggestions on how to approach this problem?

**Comment by jakobnissen** [comment]
FWIW, Rust would do it something like this
```
fn foo(x: Edit) {
    match x.x {
        Indel::Insertion => println!("Insertion at position {}", x.pos),
        Indel::Deletion => println!("Deletion at position {}", x.pos)
    }
}
```
i.e. because the match statement is defined in a local scope, it has access to the other variables in the scope.

**Comment by MasonProtter** [comment]
Mhm, yes this is something I'm really not happy with in the `@case` macro. Not only is the syntax weird, but it doesn't give good error messages if you try and use it the way you'ex expect :( 

 MLStyle.jl handles this sort of use-case better, you'd just do
```julia
using SumTypes, MLStyle

@sum_type Indel begin
    Insertion()
    Deletion()
end

struct Edit
    pos::UInt
    x::Indel
end

@as_record Indel

function report(e::Edit)
    @match e.x begin
        Indel(::Insertion) => println("Insertion at position $(e.pos)")
        Indel(::Deletion)  => println("Deletion at position $(e.pos)")
    end
end

report(Edit(10, Deletion()))

#+RESULTS:
 Deletion at position 10
```
The only real downside of MLStyle.jl here is that it can't check ahead of time if your pattern cases are exhaustive, which may or may not be a big deal.

One potential thing I could do is use MLStyle to generate a template match function for each sum type member to get the best of both worlds here. How do you feel about this package having MLStyle.jl as a dependency?

**Comment by MasonProtter** [comment]
Yeah fair. In the near future I'll try to make a `@cases` macro that behaves like a (much) more restricted version of `MLStyle.@match` and only works on sumtypes.

**Comment by MasonProtter** [comment]
Finally implemented in https://github.com/MasonProtter/SumTypes.jl/commit/21fea6e6831728ad9953d7ea2933c4fe32e18a9a
