### ISSUE TITLE
Inner constructors for variants

### ISSUE THREAD

**Issue by jakobnissen** [MasonProtter/SumTypes.jl#11]
Ref #6 

There is currently no way of enforcing invariants on variants, because you can't access their inner constructor.
One easy option is to do the following:
* Define an unexported struct `struct Unsafe end`
* The inner constructor for a variant `MyVariant{A,B}(::A, ::B, ::Int)` is then `MyVariant{A,B}(::Unsafe, ::A, ::B, ::Int)`
* An outer constructor `MyVariant{A,B}(a::A, b::B, c::Int) = MyVariant{A,B}(Unsafe(), a, b, c)` is added by default. This can then be overwritten.

**Comment by MasonProtter** [comment]
This is a good idea, I like it.

**Comment by MasonProtter** [comment]
Closed by https://github.com/MasonProtter/SumTypes.jl/commit/21fea6e6831728ad9953d7ea2933c4fe32e18a9a
