### ISSUE TITLE
Dealing with extra parameters in recursive sumtypes

### ISSUE THREAD

**Issue by MilesCranmer** [MasonProtter/SumTypes.jl#30]
Hey @MasonProtter, really nice package.

Is there a way I can make a recursive SumType which uses the correct parametrized field type?

For example, say I want to make a linked list, with a separate type for the end of the list:

```julia
@sum_type LinkedList begin
    BranchNode(val::Float64, child::LinkedList)
    EndNode(val::Float64)
end
```

However, this `LinkedList` type referenced in `BranchNode` is actually generic and will incur type inference issues, as the sum type is parametrized:

```julia
julia> typeof(BranchNode(0.1, EndNode(0.1)))
LinkedList{8, 1, UInt8}
```

Is there a way I can get this same parametrization within the `@sum_type` macro, so that I may use it to build recursive SumTypes?

Cheers,
Miles

**Comment by MilesCranmer** [comment]
One solution would be to have the macro find all instances of the **same sum type within the scope**, and add additional parameters to them. So, for example,

```julia
@sum_type LinkedList{T} begin
    BranchNode(val::T, child::LinkedList{T})
    EndNode(val::T)
end
```

would have the referenced type expanded to

```julia
BranchNode(val::T, child::LinkedList{T,8,1,UInt8})
```

**Comment by MasonProtter** [comment]
Ah good point, I didn't think of that. Hmm, I'll need to think about the best way to approach this, it's actually a little tricky.

**Comment by MilesCranmer** [comment]
Anything I can help with on this?

**Comment by MasonProtter** [comment]
Hey @MilesCranmer I don't think so. I've made a big overhaul going back to unions, but being smarter about some thing while handling them in #49, so there won't be any extra type parameters after that merges.

**Comment by MilesCranmer** [comment]
Nice!!
