### ISSUE TITLE
Default `@cases`?

### ISSUE THREAD

**Issue by MilesCranmer** [MasonProtter/SumTypes.jl#31]
I was wondering if it is possible to have a default branch in a `@cases`? For some methods it only makes sense to write logic for a few of the possible types, and throw an error if an unexpected type is passed. However, currently this requires one to write out all unexpected types, rather than a default.

**Comment by MasonProtter** [comment]
yeah I've been thinking for a little while how to support this, it's actually kinda hard to have a default branch without dynamic dispatch, at least if you want to unpack. I think what I'll do instead is have a syntax like
```julia
@cases x begin
    A(a, b) => f(a, b)
    B(c) => g(c)
    {C, D, E}(d) => h(d)
end
```
So that writing `{C, D, E}(d) => h(d)` gets expanded to
```
C(d) => h(d)
D(d) => h(d)
E(d) => h(d)
```
I haven't decided exactly how that should look though.

**Comment by mfiano** [comment]
Yes, I requested this feature on Zulip a couple of weeks ago, and just now went to add an issue for it before stumbling on this.

I agree that it is a difficult trade-off to make here. We can't simply use `_`, as we also need to unpack arbitrary variants, some of which may want to also be skipped with `_`, and in doing so we may want to refer to the default variable binding on the rhs.

Even more, we may want nested `@cases`, and refer to bindings in outer scope.

The solution @MasonProtter provided is sane to work around all these syntax limitations, but I do not know what other implications it may have.

From an API perspective, I'm not sure I like the curly braces used in that context. I think square brackets or even round, would connote the semantics of it expanding into a *collection* of branches.
