### ISSUE TITLE
sum types are not `isbits`

### ISSUE THREAD

**Issue by Krastanov** [MasonProtter/SumTypes.jl#52]
I was surprised to observe that sum types are not `isbits`. In my (flawed) mental model of this library, one of the benefits is that it provides for neat memory-contiguous storage of vectors of variants (or at least I thought memory-contiguous storage in julia vectors is possible only for isbits types).

It seems that was indeed the case in 0.4, but it was changed in 0.5 (see examples below).

The `isbits` property would be very valuable for me, because it would make it easy to dispatch over an array of variants in a loop on a GPU (because the GPU kernel macros do not seem to work for non-isbits arguments).

Hence I have two questions:

- Is there an easy way to make my variants `isbits`?
- Is there some other way to use instances of variants as arguments of a gpu kernel?

Examples of 0.4 vs 0.5 behavior:

```
# on 0.4
julia> @sum_type myST begin
           A
           B(::Int)
           C(::Int, ::Int)
       end

julia> A |> isbits
true

julia> A |> sizeof
24

julia> B(1) |> isbits
true

julia> B(1) |> sizeof
24
```

```
# on 0.5
julia> @sum_type myST begin
           A
           B(::Int)
           C(::Int, ::Int)
       end

julia> A |> isbits
false

julia> A |> sizeof
24

julia> B(1) |> isbits
false

julia> B(1) |> sizeof
24

julia> A.data |> isbits
true
```

**Comment by MasonProtter** [comment]
Hey @Krastanov really sorry for the late reply, I've been in the middle of a big move. Yes, technically these objects are no longer "isbits" but they *are* effectively bits values. One way to see this is to use `Base.allocatedinline(::Type)`:
```julia
julia> using SumTypes

julia> @sum_type myST begin
           A
           B(::Int)
           C(::Int, ::Int)
       end

julia> isbitstype(myST)
false

julia> Base.allocatedinline(myST)
true
```
What's going on here is that `myST` is storing a value which is an `isbitsunion`:
```julia
julia> only(fieldtypes(myST))
Union{SumTypes.Variant{:A, (), Tuple{}}, SumTypes.Variant{:B, (:_1,), Tuple{Int64}}, SumTypes.Variant{:C, (:_1, :_2), Tuple{Int64, Int64}}}

julia> Base.isbitsunion(ans)
true
```

As far as I'm aware this **should** work fine with GPU code though, do you have any examples where the GPU is unhappy? E.g. here's an example of it working fine for me:
```julia
julia> using CUDA

julia> let v = cu([A, B(1), C(1, 2)])
           map(v) do x
               @cases x begin
                   A => B(1)
                   B(x) => C(x, 2)
                   C(x, y) => A
               end
           end
       end
3-element CuArray{myST, 1, CUDA.Mem.DeviceBuffer}:
 B(1)::myST
 C(1, 2)::myST
 A::myST
```
If you're getting errors related to sumtypes not being `isbits`, it might just be an over-pessimistic check somewhere in the GPU pipeline.

**Comment by Krastanov** [comment]
This introduces me to a few concepts I was not aware of: `allocatedinline` and `isbitsunion`. I will need to do some prototyping to see where exactly the GPU code issue is. I will close this issue for the moment as it does not seem the underlying problem I have is with SumTypes.jl.

Thank you for the detailed explanation!
