### ISSUE TITLE
default in `@cases` when unpacking is not necessary

### ISSUE THREAD

**Issue by Krastanov** [MasonProtter/SumTypes.jl#55]
I have a situation in which a sumtype instance will be passing through "filters", where they are either "consumed" if they are a specific particular variant or passed on to the next "filter".

Is an additional "default" option possible, as discussed in https://github.com/MasonProtter/SumTypes.jl/issues/31  ?

Opening a new issue, because I have the impression the conversation in 31 was focused on default with unpacking

**Comment by MasonProtter** [comment]
Should now work with #56! Will be released as version 0.5.1 and available on the General registry once this finishes: https://github.com/JuliaRegistries/General/pull/95659

**Comment by Krastanov** [comment]
Wow, that was amazingly quick! Thank you, it is much appreciated!

**Comment by MasonProtter** [comment]
Happy to help!
