### ISSUE TITLE
getproperty for a SumType

### ISSUE THREAD

**Issue by Tortar** [MasonProtter/SumTypes.jl#58]
I think that making the package compatible with accessing data through `getproperty` (and so also the dot syntax) would make this package easier to integrate with other packages, e.g. I would like that this wouldn't error

```julia
julia> using SumTypes

julia> @sum_type AT begin
           A(x::Int, y::Int)
           B(x::Int, z::Float64)
       end

julia> a = A(1, 1)
A(1, 1)::AT

julia> a.x
ERROR: type AT has no field x
Stacktrace:
 [1] getproperty(x::AT, f::Symbol)
   @ Base ./Base.jl:37
 [2] top-level scope
   @ REPL[4]:1
```

**Comment by MasonProtter** [comment]
I've now explicitly disabled this: https://github.com/MasonProtter/SumTypes.jl/pull/59

If you really need to access the internals without `@cases`, you should use `getfield`.

**Comment by Abhishek-1Bhatt** [comment]
Hello, we use `SumTypes` for our tag system in QuantumSavory.jl and there's a lot indexing there, which causes a lot of breakage with the new release. Would you suggest replacing it with `getfield`, as in can we expect it to be a stable part of the api for `SumTypes` ?

**Comment by MasonProtter** [comment]
Ah crap, sorry for breaking your code @Abhishek-1Bhatt, can you explain what you were using `getproperty` for? The package was not really designed for one to be interacting with the insides of a sum type. I considered the internals of a SumType to be package internals that can change anytime depending on the implementation needs of the package. But in practice they'll probably be somewhat stable.

There is a function `SumTypes.unwrap` though whose job is to open up a sumtype and return the thing it had stored inside, so if you really need to get inside, I'd recommend using that function.

**Comment by Abhishek-1Bhatt** [comment]
We use tags to store information about which node we're entangled with in a network of nodes. This information is updated when  an EntanglementSwap happens and the nodes is now connected to another node, hence it requires querying the nodes about tag data at a lot of places. This functionality is implemented using SumTypes. `SumTypes.unwrap` seems to be a good fix for it

**Comment by MasonProtter** [comment]
So why are you doing that update using `getproperty` and not using `@cases`? I'm just trying to figure out if there's some functionality missing from `@cases` here...

**Comment by Abhishek-1Bhatt** [comment]
We have all the possible cases for tags implemented as a sumtype:
https://github.com/QuantumSavory/QuantumSavory.jl/blob/fdcbe418f7bcba5956e1db1cbf629ff76f21ebf1/src/tags.jl#L1-L19

but then, an individual tag, lets say [this](https://github.com/QuantumSavory/QuantumSavory.jl/blob/fdcbe418f7bcba5956e1db1cbf629ff76f21ebf1/src/ProtocolZoo/ProtocolZoo.jl#L30) `EntanglementCounterpart` tag would be just one of the types declared  as a sumtype, which contains the entanglement information in the tag, which we need to query. The problem is that `SumTypes` perfectly fits the application here, but the way we use it isn't how it was intended, I guess 😅

**Comment by Abhishek-1Bhatt** [comment]
Thanks, but I have switched to using `unwrap` , so no worries from my side now, although its always a good idea if you have the time

**Comment by MasonProtter** [comment]
Yeah I'll do it like this in case someone gets an old version of your package but a new version of SumTypes.
