### ISSUE TITLE
Adding the package installs version 5.5 instead of 5.7

### ISSUE THREAD

**Issue by Tortar** [MasonProtter/SumTypes.jl#76]
I'd like to use that version because of the latest improvement, could you please help with this @MasonProtter? Thank you

Indeed the `Releases` section on Github is still on 5.5 of 3 weeks ago

**Comment by MasonProtter** [comment]
My bad, I accidentally double-bumped the version number to 5.7 so it failed to register. I've de-bumped to 5.6 and it's now awaiting registration here: https://github.com/JuliaRegistries/General/pull/100748
